"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, CircleDollarSign, Download, Eye, RefreshCw, ShieldAlert, TrendingUp, X } from "lucide-react";

type Regime={regime:string;regimeLabel:string;confidence:number;activeStrategy:string;exposureMin:number;exposureMax:number;reasons:string[];missingFields:string[];updatedAt:string|null;lastSwitchedAt?:string|null;indicators?:Record<string,unknown>};
type Candidate={rank:number;stockCode:string;stockName:string;marketType:string;subIndustry:string;strategyType:"CRASH"|"RECOVERY"|"RANGE"|"BREAKOUT";strategyName:string;totalScore:number;healthScore:number;previousHealthScore:number|null;currentPrice:number;entryPriceLow:number;entryPriceHigh:number;breakoutPrice:number;stopLossPrice:number;targetPrice1:number;targetPrice2:number;allocationPercent:number;relativeStrength:number;volumeStatus:string;foreignNetBuy:number|null;investmentTrustNetBuy:number|null;holder400Change:number|null;holder1000Change:number|null;retailHolderChange:number|null;marginChange:number|null;industryStrength:number;falseBreakoutRisk:number;status:string;statusLabel:string;scoreBreakdown:Record<string,unknown>;selectedReasons:string[];riskReasons:string[];missingData:string[];quoteSource:string;quoteTimestamp:string};
type Industry={subIndustry:string;strengthScore:number;strengthRank:number;return1d:number|null;return5d:number|null;continuationDays:number};
type ScannerStatus={status:string;lastRunAt:string|null;lastSuccessAt:string|null;lastError:string|null;nextScanSeconds:number};
type Monitoring={stockCode:string;stockName:string;strategyType:string;addedDate:string;triggerPrice:number;stopLossPrice:number;targetPrice1:number;targetPrice2:number;allocationPercent:number;healthScore:number;monitorStatus:string;lastSignal:string|null;updatedAt:string};
type PaperTrade={id:number;stockCode:string;stockName:string;strategyType:string;quantityShares:number;quantityLots:number;entryPrice:number;entryTime:string;entryReason:string;stopLossPrice:number;targetPrice1:number;targetPrice2:number;lastPrice:number;status:"open"|"closed";exitPrice:number|null;exitTime:string|null;exitReason:string|null;grossProfit:number;tradingCost:number;netProfit:number;returnPercentage:number;unrealizedProfit:number;updatedAt:string};
type Performance={mode:"paper";period:string;assumption:string;summary:{totalTrades:number;closedTrades:number;openTrades:number;wins:number;losses:number;breakeven:number;winRate:number;grossProfit:number;tradingCost:number;netProfit:number;unrealizedProfit:number;averageProfit:number};openPositions:PaperTrade[];closedTrades:PaperTrade[]};

async function request<T>(path:string, userId:string, init?:RequestInit){const response=await fetch(path,{...init,headers:{...(init?.headers??{}),"x-user-id":userId},cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"資料讀取失敗");return body as T;}
const n=(value:number|null,digits=1)=>value==null?"—":value.toLocaleString("zh-TW",{maximumFractionDigits:digits});
const money=(value:number)=>`${value>=0?"+":"−"}${Math.abs(value).toLocaleString("zh-TW",{maximumFractionDigits:0})} 元`;
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;

export function AdaptiveElectronicPage({userId,onSelectStock}:{userId:string;onSelectStock:(symbol:string)=>void}){
  const [regime,setRegime]=useState<Regime|null>(null),[items,setItems]=useState<Candidate[]>([]),[monitoring,setMonitoring]=useState<Monitoring[]>([]),[industries,setIndustries]=useState<Industry[]>([]),[scanner,setScanner]=useState<ScannerStatus|null>(null),[performance,setPerformance]=useState<Performance|null>(null),[selected,setSelected]=useState<Candidate|null>(null),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false),[error,setError]=useState(""),[backtest,setBacktest]=useState<Record<string,unknown>|null>(null);
  const load=useCallback(async()=>{if(!userId)return;setLoading(true);setError("");try{const [r,c,i,s,p,m]=await Promise.all([request<Regime>("/api/adaptive-electronic/market-regime",userId),request<{items:Candidate[]}>("/api/adaptive-electronic/candidates",userId),request<{items:Industry[]}>("/api/adaptive-electronic/industries",userId),request<ScannerStatus>("/api/adaptive-electronic/status",userId),request<Performance>("/api/adaptive-electronic/performance",userId),request<{items:Monitoring[]}>("/api/adaptive-electronic/monitoring",userId)]);setRegime(r);setItems(c.items);setIndustries(i.items);setScanner(s);setPerformance(p);setMonitoring(m.items);}catch(reason){setError(reason instanceof Error?reason.message:"載入失敗");}finally{setLoading(false);}},[userId]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),60_000);return()=>clearInterval(timer);},[load]);
  const monitor=async(item:Candidate)=>{try{await request("/api/adaptive-electronic/monitor",userId,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stock_code:item.stockCode})});alert(`${item.stockName} 已加入監控區`);}catch(reason){alert(reason instanceof Error?reason.message:"加入失敗");}};
  const runBacktest=async(item:Candidate,years:number)=>{setBacktest({loading:true});try{setBacktest(await request<Record<string,unknown>>("/api/adaptive-electronic/backtest",userId,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stockCode:item.stockCode,strategyType:item.strategyType,years})}));}catch(reason){setBacktest({error:reason instanceof Error?reason.message:"回測失敗"});}};
  const exportMonthlyPerformance=async()=>{setExporting(true);try{const now=new Date(),month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;const report=await request<Performance>(`/api/adaptive-electronic/performance?month=${month}&limit=500`,userId);const formatTime=(value:string|null)=>value?new Date(value).toLocaleString("zh-TW",{hour12:false}):"";const rows:unknown[][]=[
    ["AI選股機器人本月模擬績效表"],["月份",month],["報表產生時間",formatTime(new Date().toISOString())],["計算說明",report.assumption],[],
    ["完成交易",report.summary.closedTrades,"持有中",report.summary.openTrades,"獲利筆數",report.summary.wins,"虧損筆數",report.summary.losses,"勝率",`${report.summary.winRate}%`],
    ["已實現淨損益",report.summary.netProfit,"未實現損益",report.summary.unrealizedProfit,"交易成本",report.summary.tradingCost,"平均每筆",report.summary.averageProfit],[],
    ["狀態","股票代號","股票名稱","策略","張數","買進時間","買進價","賣出時間","賣出價／現價","毛損益","交易成本","淨損益／未實現","報酬率","買進原因","賣出原因"],
    ...report.closedTrades.map((trade)=>["已賣出",trade.stockCode,trade.stockName,trade.strategyType,trade.quantityLots,formatTime(trade.entryTime),trade.entryPrice,formatTime(trade.exitTime),trade.exitPrice,trade.grossProfit,trade.tradingCost,trade.netProfit,`${trade.returnPercentage}%`,trade.entryReason,trade.exitReason]),
    ...report.openPositions.map((trade)=>["持有中",trade.stockCode,trade.stockName,trade.strategyType,trade.quantityLots,formatTime(trade.entryTime),trade.entryPrice,"",trade.lastPrice,"","",trade.unrealizedProfit,"",trade.entryReason,"尚未賣出"]),
  ];const csv="\ufeff"+rows.map((row)=>row.map(csvCell).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`AI選股機器人_本月績效_${month}.csv`;anchor.click();URL.revokeObjectURL(url);}catch(reason){alert(reason instanceof Error?reason.message:"匯出失敗");}finally{setExporting(false);}};
  const tone=regime?.regime.toLowerCase()??"uncertain";
  return <section className="adaptive-page">
    <div className="adaptive-heading"><div><span className="eyebrow">上市／上櫃全電子股＋低軌衛星＋玻纖布＋廠務工程</span><h1>AI選股機器人</h1><p>新進場訊號只在 09:00～13:20 有效；13:20 後選到的股票一律列為隔日觀察並重新確認。</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={16} className={loading?"spin":""}/>更新</button></div>
    {error&&<div className="error-banner">{error}</div>}
    <div className={`regime-hero ${tone}`}><div className="regime-light"/><div><small>當前市場狀態</small><strong>{regime?.regimeLabel??"等待首次掃描"}</strong><p>{regime?.reasons?.slice(0,3).join("；")??"正在等待官方資料"}</p></div><div className="regime-stat"><span>信心分數</span><b>{n(regime?.confidence??null,0)}</b></div><div className="regime-stat"><span>啟用策略</span><b>{regime?.activeStrategy??"—"}</b></div><div className="regime-stat"><span>建議總持股</span><b>{regime?`${regime.exposureMin}～${regime.exposureMax}%`:"—"}</b></div><div className="regime-stat"><span>最近切換</span><b>{regime?.lastSwitchedAt?new Date(regime.lastSwitchedAt).toLocaleString("zh-TW",{hour12:false}):"—"}</b></div></div>
    {regime?.regime==="CRASH"&&<div className="crash-defense"><ShieldAlert/><div><strong>崩盤防守模式已啟用</strong><p>停止突破與一般低接，不發直接買進訊號，只保留抗跌電子股等待止跌。</p></div></div>}
    <div className="adaptive-grid"><div className="adaptive-card"><h2><TrendingUp size={18}/>電子次產業強度</h2><div className="industry-ranks">{industries.slice(0,10).map((item)=><div key={item.subIndustry}><b>#{item.strengthRank}</b><span>{item.subIndustry}</span><i style={{width:`${item.strengthScore}%`}}/><strong>{n(item.strengthScore,0)}</strong><small>{n(item.return5d)}%</small></div>)}</div></div><div className="adaptive-card market-sources"><h2><Activity size={18}/>資料與風險狀態</h2><p>掃描器：{scanner?.status==="running"?`運行中・每 ${scanner.nextScanSeconds} 秒掃描`:scanner?.status??"讀取中"}</p><p>最後成功：{scanner?.lastSuccessAt?new Date(scanner.lastSuccessAt).toLocaleString("zh-TW",{hour12:false}):"尚未成功"}</p><p>市場更新：{regime?.updatedAt?new Date(regime.updatedAt).toLocaleString("zh-TW",{hour12:false}):"尚未更新"}</p><p>缺少欄位：{regime?.missingFields?.length?regime.missingFields.join("、"):"無"}</p><p className="notice"><AlertTriangle size={14}/>缺少的資料不會用假數字補齊，相關分數直接不加分。</p></div></div>
    <section className="adaptive-performance-card">
      <div className="adaptive-performance-title"><div><span className="eyebrow">AI PAPER PERFORMANCE</span><h2><CircleDollarSign size={19}/>模擬買賣與績效</h2><p>{performance?.assumption??"只有正式進場訊號才會建立模擬交易。"}</p></div><div className="adaptive-performance-actions"><strong>勝率 {n(performance?.summary.winRate??0,2)}%</strong><button onClick={()=>void exportMonthlyPerformance()} disabled={exporting}><Download size={14}/>{exporting?"匯出中":"匯出本月績效表"}</button></div></div>
      <div className="adaptive-performance-summary">
        <article><span>已完成交易</span><b>{performance?.summary.closedTrades??0} 筆</b><small>獲利 {performance?.summary.wins??0}／虧損 {performance?.summary.losses??0}</small></article>
        <article><span>持有中</span><b>{performance?.summary.openTrades??0} 檔</b><small>尚未計入勝率</small></article>
        <article className={(performance?.summary.netProfit??0)>=0?"profit":"loss"}><span>已實現總損益</span><b>{money(performance?.summary.netProfit??0)}</b><small>交易成本 {n(performance?.summary.tradingCost??0,0)} 元</small></article>
        <article className={(performance?.summary.unrealizedProfit??0)>=0?"profit":"loss"}><span>未實現損益</span><b>{money(performance?.summary.unrealizedProfit??0)}</b><small>持有部位估算</small></article>
        <article><span>平均每筆</span><b>{money(performance?.summary.averageProfit??0)}</b><small>只計已完成交易</small></article>
      </div>
      <div className="adaptive-trade-columns">
        <div><h3>目前模擬持股</h3>{performance?.openPositions.length?<div className="adaptive-trade-table"><table><thead><tr><th>股票</th><th>買進</th><th>現價</th><th>未實現損益</th><th>時間</th></tr></thead><tbody>{performance.openPositions.map((trade)=><tr key={trade.id}><td><b>{trade.stockCode}</b><span>{trade.stockName}</span></td><td>{n(trade.entryPrice,2)}<span>{n(trade.quantityLots,2)} 張</span></td><td>{n(trade.lastPrice,2)}</td><td className={trade.unrealizedProfit>=0?"profit":"loss"}>{money(trade.unrealizedProfit)}</td><td>{new Date(trade.entryTime).toLocaleString("zh-TW",{hour12:false})}</td></tr>)}</tbody></table></div>:<p className="adaptive-trade-empty">尚無正式進場訊號，因此沒有模擬持股。</p>}</div>
        <div><h3>已完成買賣紀錄</h3>{performance?.closedTrades.length?<div className="adaptive-trade-table"><table><thead><tr><th>股票</th><th>買進／賣出</th><th>淨損益</th><th>報酬率</th><th>賣出原因</th></tr></thead><tbody>{performance.closedTrades.map((trade)=><tr key={trade.id}><td><b>{trade.stockCode}</b><span>{trade.stockName}</span></td><td>{n(trade.entryPrice,2)} → {n(trade.exitPrice,2)}<span>{trade.exitTime?new Date(trade.exitTime).toLocaleString("zh-TW",{hour12:false}):"—"}</span></td><td className={trade.netProfit>=0?"profit":"loss"}>{money(trade.netProfit)}</td><td className={trade.returnPercentage>=0?"profit":"loss"}>{trade.returnPercentage>=0?"+":""}{n(trade.returnPercentage,2)}%</td><td>{trade.exitReason??"—"}</td></tr>)}</tbody></table></div>:<p className="adaptive-trade-empty">目前尚無完成的模擬交易；勝率會在第一筆賣出後開始計算。</p>}</div>
      </div>
      <footer><AlertTriangle size={14}/>這是依 AI 正式訊號建立的模擬績效，不代表使用者或券商帳戶實際買賣，也不保證未來獲利。</footer>
    </section>
    <div className="adaptive-table-card"><div className="table-title"><div><h2>跨日追蹤</h2><p>前一交易日選到的股票會保留在這裡，不會因今日重新排名而消失。</p></div><span>{monitoring.length} 檔</span></div>{!monitoring.length?<div className="adaptive-empty">目前沒有跨日追蹤股票</div>:<div className="adaptive-table-wrap"><table><thead><tr><th>股票</th><th>選入日期</th><th>策略</th><th>健康度</th><th>觸發價</th><th>停損</th><th>目標價</th><th>狀態</th></tr></thead><tbody>{monitoring.map((item)=><tr key={item.stockCode}><td><button className="stock-link" onClick={()=>onSelectStock(item.stockCode)}><b>{item.stockCode}</b><span>{item.stockName}</span></button></td><td>{item.addedDate}</td><td>{item.strategyType}</td><td>{n(item.healthScore,0)}</td><td>{n(item.triggerPrice,2)}</td><td>{n(item.stopLossPrice,2)}</td><td>{n(item.targetPrice1,2)}／{n(item.targetPrice2,2)}</td><td><span className="candidate-status waiting_confirmation">持續監控</span></td></tr>)}</tbody></table></div>}</div>
    <div className="adaptive-table-card"><div className="table-title"><div><h2>電子與指定題材候選區</h2><p>最多列出 20 檔；沒有合格股票時不會為了湊滿 5 檔而降標準。</p></div><span>{items.length} 檔</span></div>{!loading&&!items.length?<div className="adaptive-empty">目前沒有符合進場標準的股票</div>:<div className="adaptive-table-wrap"><table><thead><tr><th>排名</th><th>股票</th><th>次產業／策略</th><th>分數／健康度</th><th>最新價格</th><th>進場區／突破價</th><th>停損／目標</th><th>資金</th><th>籌碼</th><th>狀態</th><th>操作</th></tr></thead><tbody>{items.map((item)=><tr key={item.stockCode}><td>#{item.rank}</td><td><button className="stock-link" onClick={()=>onSelectStock(item.stockCode)}><b>{item.stockCode}</b><span>{item.stockName}・{item.marketType}</span></button></td><td><b>{item.subIndustry}</b><span>{item.strategyName}</span></td><td><b>{n(item.totalScore,0)}</b><span>健康 {n(item.healthScore,0)} {item.previousHealthScore==null?"":item.healthScore>item.previousHealthScore?"↑":item.healthScore<item.previousHealthScore?"↓":"→"}</span></td><td>{n(item.currentPrice,2)}<span>{item.quoteSource}</span></td><td>{n(item.entryPriceLow,2)}～{n(item.entryPriceHigh,2)}<span>突破 {n(item.breakoutPrice,2)}</span></td><td>{n(item.stopLossPrice,2)}<span>目標 {n(item.targetPrice1,2)}／{n(item.targetPrice2,2)}</span></td><td>{n(item.allocationPercent)}%</td><td><span>外資 {n(item.foreignNetBuy,0)}</span><span>投信 {n(item.investmentTrustNetBuy,0)}</span><span>400張 {n(item.holder400Change,2)}</span><span>千張 {n(item.holder1000Change,2)}</span></td><td><span className={`candidate-status ${item.status}`}>{item.statusLabel}</span></td><td><div className="row-actions"><button onClick={()=>setSelected(item)}><Eye size={14}/>原因</button><button onClick={()=>void monitor(item)}>監控</button></div></td></tr>)}</tbody></table></div>}</div>
    {selected&&<div className="adaptive-modal-backdrop" onClick={()=>setSelected(null)}><article className="adaptive-modal" onClick={(e)=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">{selected.stockCode} {selected.stockName}</span><h2>{selected.strategyName}・{selected.statusLabel}</h2><div className="reason-columns"><div><h3>入選與加分項目</h3>{selected.selectedReasons.map((x)=><p key={x}>✓ {x}</p>)}</div><div><h3>扣分與主要風險</h3>{selected.riskReasons.length?selected.riskReasons.map((x)=><p key={x}>⚠ {x}</p>):<p>目前沒有額外風險扣分</p>}<h3>資料限制</h3>{selected.missingData.map((x)=><p key={x}>— {x}</p>)}</div></div><pre>{JSON.stringify(selected.scoreBreakdown,null,2)}</pre><div className="row-actions"><button onClick={()=>void runBacktest(selected,1)}>回測 1 年</button><button onClick={()=>void runBacktest(selected,3)}>回測 3 年</button><button onClick={()=>void runBacktest(selected,5)}>回測 5 年</button></div>{backtest&&<pre>{JSON.stringify(backtest,null,2)}</pre>}<small>資料更新：{new Date(selected.quoteTimestamp).toLocaleString("zh-TW",{hour12:false})}</small></article></div>}
  </section>;
}
