CREATE TABLE IF NOT EXISTS portfolio_settings (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(80) NOT NULL UNIQUE,
  total_capital NUMERIC(20,2) NOT NULL DEFAULT 1000000,
  minimum_cash_percentage NUMERIC(7,4) NOT NULL DEFAULT 20,
  max_total_exposure NUMERIC(7,4) NOT NULL DEFAULT 85,
  max_position_percentage NUMERIC(7,4) NOT NULL DEFAULT 20,
  max_industry_percentage NUMERIC(7,4) NOT NULL DEFAULT 35,
  max_risk_per_trade NUMERIC(7,4) NOT NULL DEFAULT 0.5,
  max_portfolio_risk NUMERIC(7,4) NOT NULL DEFAULT 3,
  maximum_add_on_count INTEGER NOT NULL DEFAULT 2,
  initial_entry_ratio NUMERIC(7,4) NOT NULL DEFAULT 40,
  first_add_on_ratio NUMERIC(7,4) NOT NULL DEFAULT 30,
  second_add_on_ratio NUMERIC(7,4) NOT NULL DEFAULT 30,
  allow_add_on BOOLEAN NOT NULL DEFAULT TRUE,
  prohibit_averaging_down BOOLEAN NOT NULL DEFAULT TRUE,
  daily_summary_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_stock_monitor (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(80) NOT NULL,
  symbol VARCHAR(12) NOT NULL,
  stock_name VARCHAR(80) NOT NULL,
  market VARCHAR(20) NOT NULL DEFAULT '上市',
  industry VARCHAR(80) NOT NULL DEFAULT '未分類',
  strategy_name VARCHAR(120) NOT NULL,
  secondary_strategies_json TEXT NOT NULL DEFAULT '[]',
  signal_id VARCHAR(120) NOT NULL,
  monitor_status VARCHAR(40) NOT NULL DEFAULT 'monitoring',
  total_score NUMERIC(7,2) NOT NULL,
  strategy_fit NUMERIC(7,2) NOT NULL,
  market_fit NUMERIC(7,2) NOT NULL,
  health_score NUMERIC(7,2) NOT NULL,
  current_price NUMERIC(20,4) NOT NULL,
  entry_min NUMERIC(20,4) NOT NULL,
  entry_max NUMERIC(20,4) NOT NULL,
  stop_loss NUMERIC(20,4) NOT NULL,
  target_1 NUMERIC(20,4) NOT NULL,
  target_2 NUMERIC(20,4) NOT NULL,
  risk_reward_ratio NUMERIC(9,4) NOT NULL,
  target_allocation_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  initial_allocation_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  first_add_on_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  second_add_on_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  suggested_initial_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  suggested_initial_quantity INTEGER NOT NULL DEFAULT 0,
  estimated_risk_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  reasons_json TEXT NOT NULL DEFAULT '[]',
  warnings_json TEXT NOT NULL DEFAULT '[]',
  quote_source VARCHAR(80) NOT NULL,
  quote_timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  expired_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_ai_monitor_user_signal UNIQUE(user_id, signal_id)
);
CREATE INDEX IF NOT EXISTS ix_ai_monitor_user_status ON ai_stock_monitor(user_id, monitor_status);

CREATE TABLE IF NOT EXISTS ai_stock_positions (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(80) NOT NULL,
  monitor_id BIGINT NOT NULL REFERENCES ai_stock_monitor(id),
  symbol VARCHAR(12) NOT NULL,
  stock_name VARCHAR(80) NOT NULL,
  industry VARCHAR(80) NOT NULL DEFAULT '未分類',
  direction VARCHAR(12) NOT NULL DEFAULT 'long',
  strategy_name VARCHAR(120) NOT NULL,
  entry_price NUMERIC(20,4) NOT NULL,
  average_cost NUMERIC(20,4) NOT NULL,
  original_quantity INTEGER NOT NULL,
  remaining_quantity INTEGER NOT NULL,
  entry_time TIMESTAMPTZ NOT NULL,
  stop_loss NUMERIC(20,4) NOT NULL,
  target_1 NUMERIC(20,4) NOT NULL,
  target_2 NUMERIC(20,4) NOT NULL,
  trailing_stop NUMERIC(20,4),
  current_price NUMERIC(20,4) NOT NULL,
  highest_price NUMERIC(20,4) NOT NULL,
  lowest_price NUMERIC(20,4) NOT NULL,
  max_unrealized_profit NUMERIC(20,2) NOT NULL DEFAULT 0,
  max_unrealized_loss NUMERIC(20,2) NOT NULL DEFAULT 0,
  realized_profit NUMERIC(20,2) NOT NULL DEFAULT 0,
  unrealized_profit NUMERIC(20,2) NOT NULL DEFAULT 0,
  return_percentage NUMERIC(10,4) NOT NULL DEFAULT 0,
  health_score NUMERIC(7,2) NOT NULL DEFAULT 80,
  latest_action VARCHAR(80) NOT NULL DEFAULT '持有中',
  position_status VARCHAR(40) NOT NULL DEFAULT 'holding',
  overnight_status BOOLEAN NOT NULL DEFAULT FALSE,
  target_allocation_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  initial_allocation_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  current_allocation_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  invested_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  available_add_on_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  add_on_count INTEGER NOT NULL DEFAULT 0,
  estimated_risk_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  industry_exposure_percentage NUMERIC(7,4) NOT NULL DEFAULT 0,
  line_exit_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  add_on_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  closed_at TIMESTAMPTZ,
  exit_price NUMERIC(20,4),
  exit_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_ai_positions_user_status ON ai_stock_positions(user_id, position_status);

CREATE TABLE IF NOT EXISTS ai_stock_add_ons (
  id BIGSERIAL PRIMARY KEY,
  position_id BIGINT NOT NULL REFERENCES ai_stock_positions(id),
  add_on_number INTEGER NOT NULL,
  suggested_price_min NUMERIC(20,4) NOT NULL,
  suggested_price_max NUMERIC(20,4) NOT NULL,
  suggested_percentage NUMERIC(7,4) NOT NULL,
  suggested_amount NUMERIC(20,2) NOT NULL,
  suggested_quantity INTEGER NOT NULL,
  actual_price NUMERIC(20,4),
  actual_quantity INTEGER,
  previous_average_cost NUMERIC(20,4) NOT NULL,
  new_average_cost NUMERIC(20,4),
  previous_stop_loss NUMERIC(20,4) NOT NULL,
  new_stop_loss NUMERIC(20,4) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'suggested',
  signal_id VARCHAR(120) NOT NULL,
  suggested_at TIMESTAMPTZ NOT NULL,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT uq_ai_add_on_stage UNIQUE(position_id, add_on_number)
);

CREATE TABLE IF NOT EXISTS ai_stock_partial_exits (
  id BIGSERIAL PRIMARY KEY,
  position_id BIGINT NOT NULL REFERENCES ai_stock_positions(id),
  quantity INTEGER NOT NULL,
  exit_price NUMERIC(20,4) NOT NULL,
  exit_time TIMESTAMPTZ NOT NULL,
  fee NUMERIC(20,2) NOT NULL DEFAULT 0,
  tax NUMERIC(20,2) NOT NULL DEFAULT 0,
  realized_profit NUMERIC(20,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_stock_alerts (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(80) NOT NULL,
  monitor_id BIGINT,
  position_id BIGINT,
  signal_id VARCHAR(120) NOT NULL,
  alert_type VARCHAR(40) NOT NULL,
  alert_level VARCHAR(20) NOT NULL,
  action VARCHAR(80) NOT NULL,
  price NUMERIC(20,4) NOT NULL,
  reason TEXT NOT NULL,
  line_push_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  CONSTRAINT uq_ai_alert_signal_action UNIQUE(user_id, signal_id, action)
);
CREATE INDEX IF NOT EXISTS ix_ai_alerts_user_created ON ai_stock_alerts(user_id, created_at DESC);
